import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Notify from "../components/Notify";
import About from "./about";
import HomePage from "./homePage";
import Pricing from "./pricing";
import Services from "./services";
import Testimonial from "./testimonial";

function Home() {
  return (
    <div>
      <Head>
        <title>Pet Care</title>
        <meta name="description" content="Generated by next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR42jjqD9OOETAsjL1dZyDQOSi5Sx98ysnXg&usqp=CAU"
        ></link>
      </Head>
      <Navbar />
      <HomePage />
      <About />
      <Services />
      <Pricing />
      <Testimonial />
      <Notify />
      <Footer />
    </div>
  );
}
export default Home;
